---
- name: Install dependencies
  xbps: name={{ item }} state=present
  with_items:
    - acl-progs
    - postgresql
    - python-psycopg2

- name: Enable PostgreSQL
  file: src=/etc/sv/postgresql dest=/var/service/postgresql owner=root group=root state=link
