---
- name: Install dependencies
  xbps:
    pkg:
      - acl-progs
      - postgresql
      - python-psycopg2
    state: present

- name: Enable PostgreSQL
  file:
    src: /etc/sv/postgresql
    dest: /var/service/postgresql
    state: link
